language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g serverless@1.72.0
before_script:
  - export NODE_OPTIONS=--max_old_space_size=8192
script: 
  # - sls deploy -v
  - sls package