language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g serverless
before_script:
  - export NODE_OPTIONS=--max_old_space_size=4096
script: 
  - sls deploy -v